site_name: 🎵Watch out! Here comes a Spider-Man🎵
site_url: https://josh-wong.github.io/material-for-mkdocs-example-light-dark-spiderman/
site_description: Switch between the light and dark themes to see different Spideys!

# Add repository details in the top right-hand corner
repo_name: josh-wong/material-for-mkdocs-example-light-dark-spiderman
repo_url: https://github.com/josh-wong/material-for-mkdocs-example-light-dark-spiderman
# > **Warning**
# >
# > This edit page button does not work. I have prioritized the 
# multidocs site, so the edit page button on https://josh-wong.github.io 
# is correct; there doesn't seem to be a way to remove it from one site 
# and keep it on the other.
# edit_uri: blob/main/

plugins:
  # Enable the search function (currently disabled to take advantage of new search features in Material for MkDocs Insiders)
  #- search
  - git-committers:
      repository: josh-wong/material-for-mkdocs-example-light-dark-spiderman
      branch: main
  # Show the last updated date
  - git-revision-date-localized:
      type: date
  # Enable videos to be embedded
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  # Enables TechDocs support in Backstage. However, many plugins need to be disabled for TechDocs to work properly.
  #- techdocs-core

markdown_extensions:
  # Add support for abbreviations
  - abbr
  # Add support for Material for MkDocs admonitions
  - admonition
  # Add styles for buttons
  - attr_list
  # Add support for grid cards
  - md_in_html
  # Make admonitions collapsible
  - pymdownx.details
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add tooltip support
  #- pymdownx.snippets:
  #    auto_append:
  #      - includes/glossary.md
  # Add support for arbitrary nesting of code and content blocks inside each other.
  - pymdownx.superfences
  # Add support for TOC configuration
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  # Extend the theme
  #custom_dir: overrides
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_spiderman.png
  # Add icon to show repository information and link
  icon:
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  # Add light & dark theme
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: red
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: red
      accent: blue
  #features:
    # Mark announcement as read
    #- announce.dismiss
    # Add custom search functions
    #- search.suggest
    #- search.highlight
    #- search.share
    #- navigation.tracking
    #- navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - '': ''
  - 🔶RSS: 'https://josh-wong.github.io/material-for-mkdocs-example-light-dark-spiderman/feed_rss_updated.xml'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'